(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var f;function aa(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}}function ba(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var c=0;c<a.length;++c){var b=a[c];if(b&&b.Math==Math)return b}throw Error("Cannot find global object");}var ca=ba(this);
function g(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):{next:aa(a)}}var da="function"==typeof Object.create?Object.create:function(a){function c(){}c.prototype=a;return new c},m;if("function"==typeof Object.setPrototypeOf)m=Object.setPrototypeOf;else{var n;a:{var ea={a:!0},p={};try{p.__proto__=ea;n=p.a;break a}catch(a){}n=!1}m=n?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null}
var q=m,r=this||self;function t(a,c){a=a.split(".");var b=r;a[0]in b||"undefined"==typeof b.execScript||b.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===c?b[d]&&b[d]!==Object.prototype[d]?b=b[d]:b=b[d]={}:b[d]=c};function fa(a){a=u(a,"autoplay-duration");return 0<a?a:29}function u(a,c){a=parseFloat(a.getAttribute(c));isFinite(a)||(a=29);return a};/*

 SPDX-License-Identifier: Apache-2.0
*/
function v(a){var c=[],b=0,d;for(d in a)c[b++]=a[d];return c};function w(a,c){var b=void 0===b?r:b;b=b.performance;a={label:a,type:9,value:b&&b.now&&b.timing?Math.floor(b.now()+b.timing.navigationStart):Date.now()};c=c.google_js_reporting_queue=c.google_js_reporting_queue||[];2048>c.length&&c.push(a)};var y={},z=!1,A=!1;y.N=function(a){z||(z=!0,w("11",a))};y.O=function(a){A||(A=!0,w("12",a))};y.J=function(a,c,b){var d=c;d=void 0===d?r:d;if(d=(d=d.performance)&&d.now?d.now():null)a={label:a,type:void 0===b?0:b,value:d},c=c.google_js_reporting_queue=c.google_js_reporting_queue||[],2048>c.length&&c.push(a)};y.reset=function(a){A=z=!1;(a.google_js_reporting_queue=a.google_js_reporting_queue||[]).length=0};t("gwd.rumUtil",y);t("gwd.rumUtil.logContentLoading",y.N);
t("gwd.rumUtil.logContentRendered",y.O);t("gwd.rumUtil.logTimingEvent",y.J);t("gwd.rumUtil.reset",y.reset);function B(a){(0,y.J)("gwd3dmodelviewer_"+(a?"start":"stop")+"Timer_TimeToFirstFrame",window);window.Enabler&&(a?Enabler.startTimer("TimeToFirstFrame"):Enabler.stopTimer("TimeToFirstFrame"))}function C(a){window.Enabler&&(a?Enabler.startTimer("TotalEngagement"):Enabler.stopTimer("TotalEngagement"),D())}var E=0,F=0;function D(){var a=Math.floor(performance.now()/100);0==E&&(E=a);for(a-=E;F<=a;F++)Enabler.counter("TotalSessionDurationDeciseconds",!0)}
var G={Zoom:function(){Enabler.counter("Zoom",!0)},Pan:function(){Enabler.counter("Pan",!0)},Rotate:function(){Enabler.counter("Rotate",!0)},Hotspot1Click:function(){Enabler.counter("Hotspot1Click",!0)},Hotspot2Click:function(){Enabler.counter("Hotspot2Click",!0)},Hotspot3Click:function(){Enabler.counter("Hotspot3Click",!0)},Hotspot4Click:function(){Enabler.counter("Hotspot4Click",!0)},Hotspot5Click:function(){Enabler.counter("Hotspot5Click",!0)}};function H(a,c){return window.setTimeout(a,c)};function I(a,c,b){b=void 0===b?null:b;var d=document.createEvent("CustomEvent");d.initCustomEvent(a,!0,!0,b);c.dispatchEvent(d)};var J=v({R:"animation-name",ba:"auto-rotate",W:"autoplay",aa:"autoplay-duration",ca:"camera-orbit",da:"camera-target",ea:"environment-image",fa:"exposure",ga:"field-of-view",la:"max-camera-orbit",ma:"max-field-of-view",na:"min-camera-orbit",oa:"min-field-of-view",pa:"poster",qa:"reveal",ra:"shadow-intensity",sa:"shadow-softness",ta:"skybox-image",ua:"src"}).concat(v({S:"ar",T:"ar-modes",U:"ar-placement",V:"ar-scale",ka:"ios-src"})),ha=J.concat(v({ha:"gesture-cue-duration",ia:"gesture-cue-icon",ja:"gesture-cue-text"})),
K=180/Math.PI;function L(){var a=HTMLElement.call(this)||this;a.i=null;a.v=!1;a.G=!1;a.B=null;a.F=null;a.l="hotspot-"+(2147483648*Math.random()|0);a.j=!1;a.D=a.M.bind(a);a.H=!1;return a}var M=HTMLElement;L.prototype=da(M.prototype);L.prototype.constructor=L;if(q)q(L,M);else for(var N in M)if("prototype"!=N)if(Object.defineProperties){var O=Object.getOwnPropertyDescriptor(M,N);O&&Object.defineProperty(L,N,O)}else L[N]=M[N];f=L.prototype;
f.connectedCallback=function(){window.Enabler&&(Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.addEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));P(this)};f.disconnectedCallback=function(){window.Enabler&&(Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH,this),Enabler.removeEventListener(studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH,this));this.m&&(clearTimeout(this.m),this.m=void 0)};
f.attributeChangedCallback=function(){P(this)};
f.handleEvent=function(a){var c=this,b=a.type,d=a.detail;switch(b){case "click":this.u&&a.target===this.h?a.stopPropagation():a.target&&ia(a.target)?(a.stopPropagation(),ja(this,a.target)):Q(this);break;case "camera-change":"user-interaction"===d.source&&(this.i&&this.i.parentNode&&this.i.parentNode.removeChild(this.i),Q(this),ka(this));a.stopPropagation();I("camera-changed",this,d);break;case "preload":case "load":this.classList.add("ready");R(this);break;case "model-visibility":if(!d.visible)return;
this.G&&(B(!1),this.G=!1,this.j=!0,la(this),I("scene-rendered",this,null),S(this).dismissPoster());break;case "poster-dismissed":requestAnimationFrame(function(){I("poster-dismissed",c,null)})}window.Enabler&&(b===studio.events.StudioEvent.FULLSCREEN_EXPAND_FINISH?(S(this).setAttribute("touch-action","none"),Enabler.reportEngagement(),D()):b===studio.events.StudioEvent.FULLSCREEN_COLLAPSE_FINISH&&(S(this).setAttribute("touch-action","pan-y"),D()))};
function S(a){a.h||(a.h=a.ownerDocument.createElement("model-viewer"),a.h.setAttribute("camera-controls",""),a.h.setAttribute("interaction-prompt","none"),a.h.setAttribute("loading","eager"),a.h.setAttribute("data-js-focus-visible",""),a.h.setAttribute("touch-action","pan-y"),a.h.addEventListener("click",a),a.h.addEventListener("model-visibility",a),a.h.addEventListener("preload",a),a.h.addEventListener("load",a),a.h.addEventListener("camera-change",a),a.h.addEventListener("poster-dismissed",a),a.appendChild(a.h));
return a.h}function la(a){if(a.hasAttribute("autoplay")){var c=S(a);c.pause();c.play();a=1E3*fa(a);0<=a&&H(function(){c.pause()},a)}}function P(a){a.m||(a.m=H(a.gwdLoad.bind(a),1))}
f.gwdLoad=function(){var a=this;this.m&&(clearTimeout(this.m),this.m=void 0);customElements.whenDefined("model-viewer").then(function(){var c=a.h?a.h.getAttribute("src"):null,b=T(a,"src",!0);if(b){b!==c&&(a.v=!1,a.classList.remove("ready"),a.G=!0,a.j=!1,B(!0));c=g(J);for(b=c.next();!b.done;b=c.next())b=b.value,"src"!==b&&T(a,b);a.h&&a.h.jumpCameraToGoal();a.syncHotspotsToViewer();a.i&&a.i.parentNode&&a.i.parentNode.removeChild(a.i);if(b=a.getAttribute("gesture-cue-icon")){a.i=a.ownerDocument.createElement("div");
a.i.classList.add("gesture-cue-container");c=a.ownerDocument.createElement("div");c.classList.add("gesture-cue-icon");c.style.backgroundImage='url("'+b+'")';b=u(a,"gesture-cue-duration");c.style.animationIterationCount=0>b?"infinite, 1":(b/2).toFixed(1)+", 1";a.i.appendChild(c);if(c=a.getAttribute("gesture-cue-text"))b=a.ownerDocument.createElement("p"),b.classList.add("gesture-cue-text"),b.textContent=c,a.i.appendChild(b);a.appendChild(a.i)}}else R(a)})};f.gwdIsLoaded=function(){return this.v};
function T(a,c,b){b=void 0===b?!1:b;var d=a.getAttribute(c);null==d||b&&!d?a.h&&a.h.removeAttribute(c):S(a).setAttribute(c,d);return a.h?a.h.getAttribute(c):null}function R(a){a.v||(a.v=!0,I("ready",a))}function U(a){a.u&&(300<Date.now()-a.L?V(a,!1):requestAnimationFrame(function(){U(a)}))}function ka(a){a.L=Date.now();window.Enabler&&Enabler.reportEngagement();a.u||V(a,!0);requestAnimationFrame(function(){U(a)})}
function V(a,c){c?(a.u=!0,document.addEventListener("mouseup",a.D),document.addEventListener("touchend",a.D),G.Rotate&&G.Rotate(),C(!0),I("interaction-start",a)):(a.u=!1,C(!1),I("interaction-end",a))}f.M=function(){this.u&&(V(this,!1),document.removeEventListener("mouseup",this.D),document.removeEventListener("touchend",this.D))};
function ja(a,c){Q(a);var b=S(a).getElementsByClassName("hotspot");for(var d=-1,e=0;e<b.length;e++)if(b[e]===c){d=e;var h=a;if(c.ownerDocument&&c.ownerDocument.body){var l=c.getElementsByClassName("hotspot-annotation");if(0!==l.length){l=l[0];l.style.transform="";h=h.getBoundingClientRect();var k=l.getBoundingClientRect(),x=k.right;k=k.bottom;var X=0,Y=0;x>h.right&&(X=Math.round(h.right-x)-5);k>h.bottom&&(Y=Math.round(h.bottom-k)-5);l.style.transform="translate3d("+X+"px, "+Y+"px, 0px)"}}c.classList.add("selected");
a.B=c}b=d;if(-1!==b){d=c.getBoundingClientRect();e=c.querySelector("h3");c=c.querySelector("p");c={name:"Hotspot"+b,index:b,screenX:Math.round(d.left+d.width/2),screenY:Math.round(d.top+d.height/2),title:e?e.textContent:"",description:c?c.textContent:""};if(window.Enabler&&(Enabler.reportEngagement(),b="Hotspot"+(b+1)+"Click",G[b]))G[b]();I("hotspot-clicked",a,c)}}function W(a){a.C||(a.C=H(a.P.bind(a),1))}
f.P=function(){this.C&&(clearTimeout(this.C),this.C=void 0);var a=S(this).getCameraOrbit(),c=a.theta+"rad",b=a.phi+"rad";a=a.radius+"m";void 0!==this.A&&(c=this.A+"deg",this.A=void 0);void 0!==this.o&&(b=this.o+"deg",this.o=void 0);void 0!==this.s&&(a=this.s+"m",this.s=void 0);var d=S(this);d.cameraOrbit=c+" "+b+" "+a;this.H&&(this.H=!1,d.jumpCameraToGoal())};f.setYaw=function(a){this.j&&(this.A=a,this.H=!0,W(this))};f.setTargetYaw=function(a){this.j&&(this.A=a,W(this))};
f.setTargetPitch=function(a){this.j&&(this.o=a,W(this))};f.incrementTargetPitch=function(a){this.j&&(this.o=void 0!==this.o?this.o+a:S(this).getCameraOrbit().phi*K+a,W(this))};f.setTargetZoom=function(a){this.j&&(this.s=a,W(this))};f.incrementTargetZoom=function(a){this.j&&(this.s=void 0!==this.s?this.s+a:S(this).getCameraOrbit().radius+a,W(this))};f.setTargetPivot=function(a,c,b){this.j&&(S(this).cameraTarget=a+"m "+c+"m "+b+"m")};
f.setTargetLocalPan=function(a,c){if(this.j){var b=S(this),d=b.getCameraTarget().z;b.cameraTarget=a+"m "+c+"m "+d+"m"}};f.setMaterialColor=function(a,c,b,d){c=[c,b,d,1];b=S(this);b=g(b.model.materials);for(d=b.next();!d.done;d=b.next())if(d=d.value,d.name===a){d.pbrMetallicRoughness.setBaseColorFactor(c);break}};f.setMaterialClearCoat=function(){};f.playAnimation=function(a){var c=S(this);c.animationName!==a&&c.setAttribute("animation-name",a);c.play()};
f.pauseAnimation=function(a){var c=S(this);c.animationName!==a&&c.setAttribute("animation-name",a);c.pause()};f.setAnimationTime=function(a,c){var b=S(this);b.animationName!==a&&b.setAttribute("animation-name",a);b.currentTime=c};f.incrementAnimationTime=function(a,c){var b=S(this);b.animationName!==a&&b.setAttribute("animation-name",a);b.currentTime+=c};f.addHotspot=function(a,c,b,d){var e=S(this);a=Z({K:e,hotspotName:a,position:c+"m "+b+"m "+d+"m",normal:"",title:"",description:"",I:!0});e.appendChild(a)};
f.setHotspotInfoCard=function(a,c,b){var d=S(this);if(a=d.querySelector('div[slot="hotspot-'+a+'"]')){var e=a.getElementsByClassName("hotspot-annotation"),h=d.ownerDocument;0===e.length?(d=h.createElement("div"),d.classList.add("hotspot-annotation"),a.appendChild(d)):d=e[0];for(;d.firstChild;)d.removeChild(d.firstChild);a=h.createElement("h3");a.textContent=c;d.appendChild(a);c=h.createElement("p");c.textContent=b;d.appendChild(c)}};f.lookAtHotspot=function(){};f.lookAtHotspotIndex=function(){};
function Q(a){a.B&&(a.B.classList.remove("selected"),a.B=null)}
function Z(a){var c=a.position,b=a.normal,d=a.title,e=a.description,h=a.I,l=a.K.ownerDocument,k=l.createElement("div");k.setAttribute("slot","hotspot-"+a.hotspotName);k.classList.add("hotspot");h&&k.setAttribute("info-card-hidden","");k.setAttribute("data-position",c);b&&k.setAttribute("data-normal",b);if(d||e)a=l.createElement("div"),a.classList.add("hotspot-annotation"),c=l.createElement("h3"),c.textContent=d,a.appendChild(c),d=l.createElement("p"),d.textContent=e,a.appendChild(d),k.appendChild(a);
return k}
f.syncHotspotsToViewer=function(){var a=S(this);if(a){for(var c=g(a.querySelectorAll(".hotspot")),b=c.next();!b.done;b=c.next())b=b.value,b.parentNode&&b.parentNode.removeChild(b);if(c=this.querySelector("gwd-3d-hotspot-container")){this.F&&(b=this.F,(b=b.ownerNode||b.owningElement||b)&&b.parentNode&&b.parentNode.removeChild(b),this.F=null,S(this).classList.remove(this.l));var d=c.getAttribute("up-image"),e=c.getAttribute("over-image"),h=c.getAttribute("down-image");b="";d&&(b+="model-viewer."+this.l+
' .hotspot { background: url("'+d+'") center / contain no-repeat; }');e&&(b+="model-viewer."+this.l+' .hotspot:hover { background: url("'+e+'") center / contain no-repeat; }');h&&(b+="model-viewer."+this.l+" .hotspot:active, model-viewer."+(this.l+' .hotspot.selected { background: url("')+h+'") center / contain no-repeat; }');d=c.getAttribute("width");e=c.getAttribute("height");if(d||e)b+="model-viewer."+this.l+" .hotspot {",d&&(b+="width: "+parseFloat(d)+"px; "),e&&(b+="height: "+parseFloat(e)+"px; "),
b+="}";d=c.getAttribute("background-color");e=c.getAttribute("font-color");h=c.getAttribute("border-color");if(d||e||h)b+="model-viewer."+this.l+" .hotspot-annotation {",d&&(b+="background-color: "+d+"; "),e&&(b+="color: "+e+"; "),h&&(b+="border-color: "+h+"; "),b+="}";b&&(S(this).classList.add(this.l),e=document,d=e.getElementsByTagName("head")[0],d||(h=e.getElementsByTagName("body")[0],d=e.createElement("head"),h.parentNode.insertBefore(d,h)),e=e.createElement("style"),e.textContent=b,d.appendChild(e),
this.F=e);b=0;c=g(c.children);for(d=c.next();!d.done;d=c.next())if(d=d.value,e=d.getAttribute("data-position")){h=d.getAttribute("data-normal")||"";var l=d.getAttribute("hotspot-name")||String(b),k=d.getAttribute("hotspot-title")||"",x=d.getAttribute("hotspot-description")||"";d=Z({K:a,hotspotName:l,position:e,normal:h,title:k,description:x,I:d.hasAttribute("info-card-hidden")});a.appendChild(d);b++}}}};function ia(a){return a.classList&&a.classList.contains("hotspot")?!0:!1}
f.getSceneGraphModel=function(){return S(this).model};f.getCameraDetails=function(){var a=S(this).getCameraOrbit(),c=a.theta,b=a.phi;a=a.radius;var d=S(this).getCameraTarget();return{yaw:c*K,pitch:b*K,zoom:a,x:d.x,y:d.y,z:d.z}};ca.Object.defineProperties(L,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return ha}}});customElements.define("gwd-3d-model-viewer",L);}).call(this);
